apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloner-api-role
  namespace: cloner
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets", "pods", "services"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["replicasets", "statefulsets"]
  verbs: ["*"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["*"]
- apiGroups: ["networking.istio.io"]
  resources: ["virtualservices"]
  verbs: ["*"]

