name: Build and Push Docker Images

on:
  push:
    branches:
      - '**'
    paths:
      - '**'
      - '!frontend/**' # Exclude frontend path to not trigger on frontend changes alone for backend builds

jobs:
  build-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/k8s-namespace-cloner-backend:${{ github.sha }}
          # Additional tag for main branch
          tags: |
            ghcr.io/${{ github.repository }}/k8s-namespace-cloner-backend:${{ github.sha }}
            ${{ github.ref == 'refs/heads/main' && 'ghcr.io/${{ github.repository }}/k8s-namespace-cloner-backend:latest' || '' }}

  build-frontend:
    runs-on: ubuntu-latest
    needs: build-backend
    if: github.ref == 'refs/heads/main' || contains(github.event.commits.*.modified, 'frontend/')
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/k8s-namespace-cloner-frontend:${{ github.sha }}
          # Additional tag for main branch
          tags: |
            ghcr.io/${{ github.repository }}/k8s-namespace-cloner-frontend:${{ github.sha }}
            ${{ github.ref == 'refs/heads/main' && 'ghcr.io/${{ github.repository }}/k8s-namespace-cloner-frontend:latest' || '' }}
